meta:
  title: Unmarshal Docs
  description: The easiest way to query Blockchain data from Ethereum, Binance Smart Chain and Polygon
  siteUrl: https://unmarshal.io
  keywords: unmarshal,docs, developer, portal, api portal, api reference docs
  lang: en-US
linkChecker:
  severity: warning
  options:
    CheckExternal: false
logo:
  image: ./images/brand-assets/img_white.svg
  altText: Unmarshal Docs
toc:
  enable: true
disableLastModified: true
oasDefinitions:
  core: ./openapi/apis/core.json
  nfts: ./openapi/apis/nfts.json
  lp-positions: ./openapi/apis/lp-positions.json
  pricestore: ./openapi/apis/pricestore.json
  tokenstore: ./openapi/apis/tokenstore.json
  top-traders: ./openapi/apis/top-traders.json
  notifications: ./openapi/apis/notifications.json
  # add links to definitions in our API registry by using a fully qualified URL.
stylesheets:
  - './static/main.css'
  - https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700;800;900&display=swap
#analytics:
  # ga:
  # note that GA doesn't work in the development environment
  #  trackingId: UA-45997213-1
#scripts:
#  - ./static/intercom.js
nav:
  - label: Pricing
    external: true
    href: https://unmarshal.io/pricing
  - label: Get API Key
    external: true
    href: https://console.unmarshal.io
  - search: true

footer:
  columns:
